// HD pixel maps for the About-timeline emblems (see PixelEmblem.vue). One string
// per row, one char per pixel, '.' = transparent. Char → fill class legend
// (colours resolved in PixelEmblem.vue from theme tokens):
//   K outline · S screen black · N phosphor green
//   G/g/Y gold base/shade/light · W/w/d white/gray/dark-gray
//   A/a/E azure base/shade/light · M/m/e mint base/shade/light
//   R/r/q red base/shade/light
// Regenerate with a paint script rather than editing pixels by hand.
export const EMBLEM_PIXEL_MAPS = {
	diploma: [
		'............................',
		'............................',
		'.KKKK..................KKKK.',
		'KWWWWK................KWWWWK',
		'KWwwdKKKKKKKKKKKKKKKKKKWwwdK',
		'KWwwdWWWWWWWRRRrWWWWWWWWwwdK',
		'KWwwdWWWWWWWRRRrWWWWWWWWwwdK',
		'KWwwdWWWWWWWRRRrWWWWWWWWwwdK',
		'KWwwdWWWWWWWRRRrWWWWWWWWwwdK',
		'KWwwdWWWWWWWRRRrWWWWWWWWwwdK',
		'KWwwdWWWWWWWRRRrWWWWWWWWwwdK',
		'KWwwdwwwwwwwRRRrwwwwwwwWwwdK',
		'KWwwdwwwwwwwRRRrwwwwwwwWwwdK',
		'KWwwdKKKKKKrrKKrrKKKKKKWwwdK',
		'KddddK....KrrKKrrK....KddddK',
		'.KKKK.....KrrKKrrK.....KKKK.',
		'...........KK..KK...........',
		'............................',
	],
	book: [
		'............................',
		'............................',
		'.KKKKKKKKKKKKKKKKKKKKKKKKKK.',
		'KAAAAAAAAAAAAAAAAAAAAAAAAAAK',
		'KAWWWWWWWWWWwAAwWWWWWWWWWWAK',
		'KAWWWWWWWWWWwAAwWWWWWWWWWWAK',
		'KAWWdddddddWwAAwWdddddddWWAK',
		'KAWWWWWWWWWWwAAwWWWWWWWWWWAK',
		'KAWWdddddddWwAAwWdddddddWWAK',
		'KAWWWWWWWWWWwAAwWWWWWWWWWWAK',
		'KAWWdddddddWwAAwWdddddddWWAK',
		'KAwwwwwwwwwwwAAwwwwwwwwwwwAK',
		'KawwwwwwwwwwwaawwwwwwwwwwwaK',
		'KaaaaaaaaaaaaaaaaaaaaaaaaaaK',
		'.KKKKKKKKKKKKKKKKKKKKKKKKKK.',
		'............................',
		'............................',
	],
	globe: [
		'........KKKKKKKK........',
		'.......KEEEEEEAAK.......',
		'.....KKEEEEEEAAAAKK.....',
		'....KEEEEEEEAAAAAAAK....',
		'....KMMMMMMAAAAAAAAK....',
		'...KEMMMMMMAAAAAAAAAK...',
		'..KEMMMMMMMAAMMMMMMAAK..',
		'..KEMMMMAAAAAMMMMMMAAK..',
		'..KEMMmmmAAAAMMMMMMAAK..',
		'..KEEEmmmAAAAAAMMMMAaK..',
		'..KEEAAAAAAAAAAMMMMaaK..',
		'..KEAAAAAAAAAAAMmmmaaK..',
		'..KAAAAAAAAAAAAAmmmaaK..',
		'..KAAAAAMMMMMAAAaaaaaK..',
		'...KAAAAMMMMMAAaaaaaK...',
		'....KAAAMmmmMAaaaaaK....',
		'....KAAAAAAAAaaaaaaK....',
		'.....KKAAAAAaaaaaKK.....',
		'.......KAAAaaaaaK.......',
		'......KKKddddddKKK......',
		'.....KwwwwwwwwwwwwK.....',
		'.....KddddddddddddK.....',
		'......KKKKKKKKKKKK......',
	],
	chart: [
		'..K........................',
		'.KwK................KKKK...',
		'.KwK...............KYYYgK..',
		'.KwK...............KGGGgK..',
		'.KwK...............KGGGgK..',
		'.KwK...........KKKKKGGGgK..',
		'.KwK..........KeeemKGGGgK..',
		'.KwK..........KMMMmKGGGgK..',
		'.KwK......KKKKKMMMmKGGGgK..',
		'.KwK.....KeeemKMMMmKGGGgK..',
		'.KwK.....KMMMmKMMMmKGGGgK..',
		'.KwK.KKKKKMMMmKMMMmKGGGgK..',
		'.KwKKeeemKMMMmKMMMmKGGGgK..',
		'.KwKKMMMmKMMMmKMMMmKGGGgK..',
		'.KwKKMMMmKMMMmKMMMmKGGGgK..',
		'.KwKKMMMmKMMMmKMMMmKGGGgK..',
		'.KwwwwwwwwwwwwwwwwwwwwwwwK.',
		'..KKKKKKKKKKKKKKKKKKKKKKK..',
		'...........................',
	],
	phone: [
		'..........................',
		'....KKKKKKKKKKKKKKKKKK....',
		'...KqqqqqqqqqqqqqqqqqqK...',
		'.KKKRRRRRRRRRRRRRRRRRRKKK.',
		'KRRRRRrRRRRRRRRRRRRRRRRRrK',
		'KRRRRRrrrrrrrrrrrrrRRRRRrK',
		'KRqRRRrKKKKKKKKKKKKRqRRRrK',
		'KRqrrRrK..........KRqrrRrK',
		'KRqrrRrK..........KRqrrRrK',
		'KRqrrRrK..........KRqrrRrK',
		'KRqRRRrK..........KRqRRRrK',
		'KRRRRRrK..........KRRRRRrK',
		'KrrrrrrK..........KrrrrrrK',
		'.KKKKKK............KKKKKK.',
		'..........................',
	],
	'gold-bars': [
		'..........KKKKKKKK..........',
		'.........KYYYYYYYYK.........',
		'........KGGGGGGGGGGK........',
		'........KGGGGGGGGGGK........',
		'.......KGGGGGGGGGGGGK.......',
		'.......KggggggggggggK.......',
		'........KKKKKKKKKKKK........',
		'...KKKKKKKK......KKKKKKKK...',
		'..KYYYYYYYYK....KYYYYYYYYK..',
		'.KGGGGGGGGGGK..KGGGGGGGGGGK.',
		'.KGGGGGGGGGGK..KGGGGGGGGGGK.',
		'KGGGGGGGGGGGGKKGGGGGGGGGGGGK',
		'KggggggggggggKKggggggggggggK',
		'.KKKKKKKKKKKK..KKKKKKKKKKKK.',
		'............................',
	],
	'terminal-42': [
		'.KKKKKKKKKKKKKKKKKKKKKKKKKK.',
		'KWWWWWWWWWWWWWWWWWWWWWWWWWWK',
		'KWwwwwwwwwwwwwwwwwwwwwwwwddK',
		'KWwwSSSSSSSSSSSSSSSSSSSSwddK',
		'KWwwSSSSSSSSSSSSSSSSSSSSwddK',
		'KWwwSSSNSSSNSSSNNNNNSSSSwddK',
		'KWwwSSSNSSSNSSSSSSSNSSSSwddK',
		'KWwwSSSNSSSNSSSSSSSNSSSSwddK',
		'KWwwSSSNNNNNSSSNNNNNSSSSwddK',
		'KWwwSSSSSSSNSSSNSSSSSSSSwddK',
		'KWwwSSSSSSSNSSSNSSSSSSSSwddK',
		'KWwwSSSSSSSNSSSNNNNNSSSSwddK',
		'KWwwSSSSSSSSSSSSSSSSSSSSwddK',
		'KWwwSSSSSSSSSSSSSSSSSSSSwddK',
		'KWwwwwwwwwwwwwwwwwwwwwwwwddK',
		'KWdddddddddddddddddddddddddK',
		'.KKKKKKKKKKKKKKKKKKKKKKKKKK.',
		'.......KKKKddddddKKKK.......',
		'......KwwwwwwwwwwwwwwK......',
		'......KddddddddddddddK......',
		'.......KKKKKKKKKKKKKK.......',
		'............................',
	],
	charger: [
		'..........................',
		'...KKKKKKKKKKK............',
		'..KeeeeeeeeeeeKK..........',
		'..KeMMMMMMMMmmddK.........',
		'..KeMSSSSSSSmmKKdK........',
		'..KeMSNNNSSSmmK.KdK.......',
		'..KeMSSSSSSSmmK.KdK.......',
		'..KeMSNNSSSSmmK.KdK.......',
		'..KeMMMMMMMMmmK.KdKK......',
		'..KeMMMMMMMMmmKKwwwdK.....',
		'..KeMMMMGGMMmmKKwwwdK.....',
		'..KeMMMGGMMMmmKKwwwdK.....',
		'..KeMMYYYYMMmmKKwwwdK.....',
		'..KeMMMMGGMMmmKKwwwdK.....',
		'..KeMMMGGMMMmmK.KGGK......',
		'..KeMMMMMMMMmmK.KGGK......',
		'..KemmmmmmmmmmK..KK.......',
		'..KemmmmmmmmmmK...........',
		'.KKKKKKKKKKKKKKKK.........',
		'KwwwwwwwwwwwwwwwwK........',
		'KwwwwwwwwwwwwwwwwK........',
		'KddddddddddddddddK........',
		'.KKKKKKKKKKKKKKKK.........',
	],
}
