// Ships when GAME_SHIPPED flips; until then /game is dev-only and builds redirect (src/main.js).
export const GAME_SHIPPED = false
export const GAME_READY = GAME_SHIPPED || import.meta.env.DEV

// The letters: plain glyph masks, `#` = stroke, 26 rows, six-cell strokes. Light, depth, outline,
// plating and wear are all derived in js/wordmark.js, so the letters are the only thing drawn by hand.
export const GAME_WORDMARK = {
	text: 'HERMES',
	glyphs: {
		H: [
			'.####........####.',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'##################',
			'##################',
			'##################',
			'##################',
			'##################',
			'##################',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'.####........####.',
		],
		E: [
			'.################.',
			'##################',
			'##################',
			'##################',
			'##################',
			'#################.',
			'######............',
			'######............',
			'######............',
			'######............',
			'###############...',
			'################..',
			'################..',
			'################..',
			'################..',
			'###############...',
			'######............',
			'######............',
			'######............',
			'######............',
			'#################.',
			'##################',
			'##################',
			'##################',
			'##################',
			'.################.',
		],
		R: [
			'.###############..',
			'#################.',
			'##################',
			'##################',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'##################',
			'##################',
			'#################.',
			'################..',
			'######..#######...',
			'######...######...',
			'######...######...',
			'######....######..',
			'######....######..',
			'######.....######.',
			'######.....######.',
			'######......######',
			'######......######',
			'######......######',
			'######......######',
			'.####........####.',
		],
		M: [
			'.#####..........#####.',
			'#######........#######',
			'########......########',
			'#########....#########',
			'#########....#########',
			'######.###..###.######',
			'######.###..###.######',
			'######.###..###.######',
			'######..######..######',
			'######..######..######',
			'######..######..######',
			'######...####...######',
			'######...####...######',
			'######....##....######',
			'######....##....######',
			'######..........######',
			'######..........######',
			'######..........######',
			'######..........######',
			'######..........######',
			'######..........######',
			'######..........######',
			'######..........######',
			'######..........######',
			'######..........######',
			'.#####..........#####.',
		],
		S: [
			'..##############..',
			'.################.',
			'##################',
			'##################',
			'##################',
			'##################',
			'######.......#####',
			'######........###.',
			'######............',
			'######............',
			'#############.....',
			'###############...',
			'.###############..',
			'...###############',
			'.....#############',
			'........##########',
			'............######',
			'............######',
			'.###........######',
			'#####.......######',
			'##################',
			'##################',
			'##################',
			'##################',
			'.################.',
			'..##############..',
		],
	},
	gap: 5,
	// how far the letters stand off the wall, in cells, down and to the right (away from the key light)
	depth: 3,
	// Brushed steel under the site's upper-left key light. The lit and shaded bands are two cells deep;
	// the very top row is the specular line and the very bottom row a thin rim light off the floor.
	ramp: {
		specular: 'star',
		light: 'silver',
		face: 'pewter',
		brushed: 'brushed',
		shade: 'gun',
		dark: 'gun',
		rim: 'pewter',
		hardware: 'graphite',
		depth: 'graphite',
		depthFar: 'iron',
		outline: 'pitch',
		glint: 'star',
	},
	// the face falls off toward the lower right by dither, between these points of the box diagonal
	shade: { from: 0.5, to: 1.1 },
	// rivets: a dark dome with a lit cell up-left of it, inset from each corner of a letter's box
	rivet: { inset: 2 },
	// Wear on a fixed seed: brushed grain runs across the faces in short horizontal runs, a few dark
	// scratches, highlights worn back to face here and there, chips out of the outer outline.
	wear: { seed: 9, run: 6, streak: 0.42, scratch: 0.02, worn: 0.06, chip: 0.03 },
	// one diagonal glint sweeps the faces every `every` ms, one cell per `step` ms, `width` cells thick
	glint: { every: 4200, step: 28, width: 3 },
}

// The holding screen (GameHolding.vue): the name plating itself up, then a status line typed under it.
export const GAME_HOLDING = {
	// The line under the name, typed in once the last plate has landed. It has one job: nobody should
	// think there is a game to play yet.
	readout: { lead: 'GAME UNDER', accent: 'CONSTRUCTION', delayMs: 500, charMs: 55 },
	// how far the name and its line lean with the cursor
	depth: 9,
	plating: {
		// the word spans this share of the frame, at no more than cellMax CSS px per cell
		span: 0.88,
		cellMax: 3,
		// cells of margin round the layout, room for the sparks
		pad: 5,
		// plates are this many cells square, cut on each letter's box so they tile the strokes
		plate: 6,
		// one plate lands per step; a letter starts once the one before is this far along
		stepMs: 48,
		overlap: 0.7,
		// a landed plate glows for this many steps and throws this many sparks that live this long
		hotSteps: 2,
		sparks: 4,
		sparkSteps: 3,
		seed: 4,
	},
	// a plate that has just landed, and the sparks it throws
	weld: { spark: 'glow', hot: 'glow' },
}
