// Ships when GAME_SHIPPED flips; until then /game is dev-only and builds redirect (src/main.js).
export const GAME_SHIPPED = false
export const GAME_READY = GAME_SHIPPED || import.meta.env.DEV

// The holding screen (GameHolding.vue): the heading over two strips of the departure's moon.
export const GAME_HOLDING = {
	lead: 'Under ',
	accent: 'construction',
	site: {
		far: { heightVh: 18, horizon: 0.42 },
		near: { heightVh: 40, horizon: 0.8 },
		at: 0.54,
		foot: 43,
		// painted steel in the warm rock ramp, `K` outline so it stands off the cold ground
		legend: {
			A: 'amber',
			D: 'dune',
			C: 'clay',
			B: 'brick',
			R: 'rust',
			E: 'ember',
			K: 'pitch',
			o: 'stone',
			b: 'bone',
			c: 'chalk',
			a: 'ash',
			s: 'soot',
			t: 'steel',
			z: 'zinc',
			f: 'frost',
			r: 'rime',
		},
		wide: {
			beacon: [36, 0],
			rows: [
				'................................KKKKDKKKKKKKKK..............................',
				'........................KKKKKKKKCCCCCCCCCCCCCCKKKKKKKKKKKKKKKKKK............',
				'..................KKKKKKCCCCCCCC...ACB........CCCCCCCCCCCCCCCCCCKKKKKKKKKK..',
				'.................KBCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCBK.',
				'.................KB.C.C.C.C.C.C.CACCCCCBC.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.CBK.',
				'.................KBC.C.C.C.C.C.C.ACCCCCB.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.BK.',
				'.................KBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBK.',
				'..................KoooooaKKKKKKKKDAACCCBBBBBBKKKKKKKKKKKKKBCBKKKKKKKKKKKKK..',
				'..................KoooooaK......KDAAAAABAEEABK............KRK...............',
				'..................KoooooaK.......KDDDDDKAAACBK............KRK...............',
				'..................KoooooaK.......KACCCBKRRRRRK............KRK...............',
				'..................KaaaaaaK.......KAC.CBKKKKKK.............KRK...............',
				'...................KKKKKK........KA.C.BK..................KRK...............',
				'.................................KAC.CBK..................KRK...............',
				'.................................KACCCBK..................KRK...............',
				'.................................KAC.CBK..................KRK...............',
				'.................................KA.C.BK..................KRK...............',
				'.................................KAC.CBK..................KRK...............',
				'.................................KACCCBK..................KRK...............',
				'.................................KAC.CBK..................KRK...............',
				'.................................KA.C.BK..................KRK...............',
				'.................................KAC.CBK..................KRK...............',
				'.................................KACCCBK.................KACBK..............',
				'.................................KAC.CBK................KKKBKKK.............',
				'.................................KA.C.BK...............KccccbbaK............',
				'.................................KAC.CBK...............KcbbbbaaK............',
				'.................................KACCCBK...............KbbbbaaK.............',
				'.................................KAC.CBK................KKKKKK..............',
				'.................................KA.C.BK..................KKKKKKK.....KKK...',
				'.................................KAC.CBK.................KAAAAAAAK...KEEEK..',
				'.................................KACCCBK.................KCCKBKCCK....KACBK.',
				'.................................KAC.CBK................KCKKKBKKKCK....KBK..',
				'.................................KA.C.BK...............KCK..KBK..KCK...KBK..',
				'.................................KAC.CBK..KKKKKKKK....KCK...KBK...KCK..KBK..',
				'.................................KACCCBK.KDDDDDDDDK..KCK....KBK....KCK.KBK..',
				'.................................KAC.CBK.KEKKEKKEK...KCK....KBK.....KCKKBK..',
				'.................................KA.C.BK..KEKKEKKEK.KCK.....KBK.....KCKKBK..',
				'............KKKKK................KAC.CBK..KKEKKEKK.KCKKKKKKKKKK......KCKBK..',
				'...........KcccbaK...............KACCCBK.KBBBBBBBBKKcbbbcbbbcbbK......KKBK..',
				'.........KKKbbbaaKKK.....KKKK....KAC.CBK..KKKBKKKK.KbbbabbbabbbKKKKKKKKKBK..',
				'........Kcccba.cccbaK...KrfftK...KA.C.BK....KBK....KcbbbcbbbcbbbcbbbcbbKBK..',
				'......KKKbbbaa.bbbaaKKKKEffzztK..KAC.CBK....KBK....KbbbabbbabbbabbbabbbKBK..',
				'.....KcccbaKcccbaKcccbaKsKssKsK.KAACCCBBK...KBK....KcbbbcbbbcbbbcbbbcbbKBK..',
				'.....KbbbaaKbbbaaKbbbaaKsKssKsKKAABBBBBBBK..KBK....KbbbabbbabbbabbbabbbKBK..',
				'.......................KKKK.............KKKKKKKKKKK....................KKKKK',
				'.......................KKK.............KKKKKKKKK.......................KKKKK',
				'......................................KKKKKKK..........................KKK..',
				'.....................................KKKKK..................................',
			],
		},
		narrow: {
			beacon: [25, 0],
			rows: [
				'.....................KKKKDKKKKKKK.......................',
				'.............KKKKKKKKCCCCCCCCCCCCKKKKKKKKKKKKKK.........',
				'........KKKKKCCCCCCCC...ACB......CCCCCCCCCCCCCCKKKKKKKK.',
				'.......KBCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCBK',
				'.......KB.C.C.C.C.C.C.ACCCCCB.C.C.C.C.C.C.C.C.C.C.C.C.BK',
				'.......KBC.C.C.C.C.C.CACCCCCBC.C.C.C.C.C.C.C.C.C.C.C.CBK',
				'.......KBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBK',
				'........KoooooaKKKKKKKDAACCCBBBBBBKKKKKKKKBCBKKKKKKKKKK.',
				'........KoooooaK.....KDAAAAABAEEABK.......KRK...........',
				'........KoooooaK......KDDDDDKAAACBK.......KRK...........',
				'........KoooooaK......KACCCBKRRRRRK.......KRK...........',
				'........KaaaaaaK......KAC.CBKKKKKK........KRK...........',
				'.........KKKKKK.......KA.C.BK.............KRK...........',
				'......................KAC.CBK.............KRK...........',
				'......................KACCCBK.............KRK...........',
				'......................KAC.CBK.............KRK...........',
				'......................KA.C.BK.............KRK...........',
				'......................KAC.CBK.............KRK...........',
				'......................KACCCBK.............KRK...........',
				'......................KAC.CBK.............KRK...........',
				'......................KA.C.BK.............KRK...........',
				'......................KAC.CBK.............KRK...........',
				'......................KACCCBK............KACBK..........',
				'......................KAC.CBK...........KKKBKKK.........',
				'......................KA.C.BK..........KccccbbaK........',
				'......................KAC.CBK..........KcbbbbaaK........',
				'......................KACCCBK..........KbbbbaaK.........',
				'......................KAC.CBK...........KKKKKK..........',
				'......................KA.C.BK...........................',
				'......................KAC.CBK...........................',
				'......................KACCCBK.............KKKKKKK.......',
				'......................KAC.CBK............KAAAAAAAK......',
				'......................KA.C.BK............KCKKBKKCK......',
				'......................KAC.CBK..KKKKKKKK.KCK.KBK.KCK.....',
				'......................KACCCBK.KDDDDDDDDKCK..KBK..KCK....',
				'......................KAC.CBK.KEKKEKKEKCK...KBK...KCK...',
				'......................KA.C.BK..KEKKEKKECK...KBK...KCK...',
				'......................KAC.CBK..KKEKKEKKKKKKKKKK....KCK..',
				'......................KACCCBK.KBBBBBBBBbbbcbbbcK....K...',
				'....KKKKK.............KAC.CBK..KKKBKKKbbbabbbabKKKKKK...',
				'...KcccbaK............KA.C.BK....KBK.KcbbbcbbbcbbbcbbK..',
				'.KKKbbbaaKKK..........KAC.CBK....KBK.KbbbabbbabbbabbbK..',
				'KcccbaKcccbaK........KAACCCBBK...KBK.KcbbbcbbbcbbbcbbK..',
				'KbbbaaKbbbaaK.......KAABBBBBBBK..KBK.KbbbabbbabbbabbbK..',
				'.............................KKKKKKKKKKK.............KKK',
				'............................KKKKKKKKK................KKK',
				'...........................KKKKKKK...................KKK',
				'..........................KKKKK.........................',
			],
		},
	},
}
